version: "3"

tasks:
  dev:
    desc: start all apps in dev the mode
    deps:
      - task: dev:web
      - task: dev:server

  dev:web:
    desc: start web localhost
    cmds:
      - pnpm dev

  dev:server:
    desc: Start server
    dir: server
    cmds:
      - pnpm dev

  fmt:
    desc: format all packages
    deps:
      - task: fmt:web
      - task: fmt:server

  fmt:web:
    desc: format web files
    cmds:
      - pnpm fmt

  fmt:server:
    desc: format server files
    dir: server
    cmds:
      - pnpm fmt

  build:
    desc: build packages then apps
    cmds:
      - pnpm tsc -b && vite build
      - cd server && pnpm tsc
  lint:
    desc: lint all the packages
    cmds:
      - pnpm eslint .
      - cd server && pnpm oxlint
  install:
    desc: install all the dependencies
    cmds:
      - pnpm install
